# Copyright 2026 Misha Brukman
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:26.04

# We want this to be an env var that only persists during the build step but is
# not part of the final image, so we're using ARG here instead of ENV which
# would keep this permanently as part of the final built image.
#
# All other similar build-time env vars are also using ARG instead of VAR.
ARG DEBIAN_FRONTEND=noninteractive

# Need to install curl first to get the Google Chrome APT key below.
# Ubuntu 26.04 base image has neither `curl` nor `wget`.
RUN apt update -qq > /dev/null && \
    apt install -qq -y \
        curl \
        > /dev/null

# Set up Google's signing key and repository for Google Chrome.
# See https://www.google.com/linuxrepositories/ for more info.
#
# We need a browser in the container for Antigravity login; just installing the
# Firefox or Chromium from Ubuntu APT repo doesn't actually work as it doesn't
# set them up as browsers that `xdg-open` will recognize for handling HTTPS
# URLs. Alternatively, installing the Snap version is problematic inside containers.
#
# Thus, we install it manually from Google's APT repo.
ARG GOOGLE_KEY="/etc/apt/trusted.gpg.d/google.asc"
RUN curl -fsSL "https://dl.google.com/linux/linux_signing_key.pub" \
    | tee "${GOOGLE_KEY}" > /dev/null
RUN echo "deb [arch=amd64 signed-by=${GOOGLE_KEY}] https://dl.google.com/linux/chrome/deb/ stable main" \
    | tee "/etc/apt/sources.list.d/google-chrome.list" > /dev/null

# Install Antigravity dependencies.
RUN apt update -qq > /dev/null && \
    apt install -qq -y \
        google-chrome-stable \
        libasound2t64 \
        libatk1.0-0 \
        libatk-bridge2.0-0 \
        libcairo2 \
        libcups2 \
        libdbus-1-3 \
        libegl1 \
        libgbm1 \
        libglib2.0-0 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libx11-xcb1 \
        > /dev/null

# Install development tools.
RUN apt install -qq -y \
        clang \
        clangd \
        gdb \
        git \
        less \
        meson \
        sudo \
        tmux \
        > /dev/null

# Ubuntu comes with a user account `ubuntu` with uid=1000, gid=1000.
# If this matches your user account, you're all set with this config.
ARG UNAME ubuntu
RUN echo "${UNAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
ARG HOME="/home/${UNAME}"
WORKDIR "${HOME}"
VOLUME "${HOME}"
USER "${UNAME}"

# Install Antigravity IDE outside of the container so it can be updated easily without
# having to rebuild the container every time.
VOLUME "/opt/antigravity-ide"

# Antigraviry requires D-Bus:
# https://antigravity.google/docs/cli/troubleshooting/#authorize-keyring-permissions
#
# Using the Wayland approach here instead of the X11 approach since Ubuntu
# 26.04 defaults to Wayland.
#
# Disabling GPU as it seems to error on startup.
CMD ["/usr/bin/dbus-run-session", "--", "/opt/antigravity-ide/antigravity-ide", "--disable-gpu"]
